Added error managment and removed some non used views
watchorpass/MovieFlick pull request #23
Opened 2024-08-28 08:30 UTC by Bitos88

2024-08-28 08:31 UTC, Bitos88 commented
![image](https://github.com/user-attachments/assets/41c7769b-9993-4359-ba56-46df3e89d798)

2024-08-28 14:49 UTC, alexmaxu approved these changes
👍

2024-08-29 09:47 UTC, franmu94 approved these changes

2024-08-29 14:06 UTC, fran-6co requested changes

2024-08-29 14:06 UTC, fran-6co commented on MovieFlick/CardStackView.swift
> +            CustomErrorView(alertTitle: "UPS... Algo ha salido mal",
Mejor en inglés para no liarla luego con el localizedstrings

> Ouch... something went wrong

2024-08-29 20:54 UTC, fran-6co approved these changes

2024-08-30 08:04 UTC, merged