Choose one movie
watchorpass/MovieFlick pull request #31
Opened 2024-09-01 08:25 UTC by alexmaxu

- [ ]

2024-09-03 16:33 UTC, fran-6co requested changes
nice!

2024-09-03 16:37 UTC, fran-6co approved these changes

2024-09-03 16:40 UTC, fran-6co commented
> nice!

my bad, me parecía que el fondo se arreglaba aqui, pero se arregla en #36

2024-09-04 07:22 UTC, alexmaxu commented on MovieFlick/MovieFlickViewModel.swift
> +            moviesWithCard = try await interactor.loadCardImages(for: movies).reversed().dropLast(17)
👍

2024-09-06 08:48 UTC, merged