Added Grid Cell Component
watchorpass/MovieFlick pull request #5
Opened 2024-08-12 15:41 UTC by fran-6co

[https://github.com/users/watchorpass/projects/1?pane=issue&itemId=74319162](<#URL#> "Task link")

2024-08-14 08:07 UTC, fran-6co commented
Improved commit for review, @Bitos88 @franmu94 @alexmaxu

2024-08-14 12:52 UTC, fran-6co commented on MovieFlick/GridCellComponent.swift
> +                .background(.ultraThinMaterial) // por si sale el placeholder popcorn, que se vea el fondo difuminado.
No hay comentarios en el último commit.

2024-08-14 15:02 UTC, Bitos88 requested changes

2024-08-14 15:02 UTC, Bitos88 commented on MovieFlick/GridCellComponent.swift
> +                .background(.thinMaterial)
Ui esto...

2024-08-14 15:03 UTC, fran-6co commented on MovieFlick/GridCellComponent.swift
> +        ZStack(alignment: .bottomLeading) {
commit antiguo

2024-08-16 07:51 UTC, Bitos88 commented
![image](https://github.com/user-attachments/assets/2f581d15-6c3e-421f-98d2-dcc47e0b27ca)

2024-08-16 08:03 UTC, alexmaxu approved these changes

2024-08-16 08:03 UTC, Bitos88 approved these changes

2024-08-16 08:03 UTC, merged