Stars component
watchorpass/MovieFlick pull request #6
Opened 2024-08-12 17:12 UTC by franmu94

Componente de estrallas para el rating

2024-08-12 18:16 UTC, Bitos88 requested changes

2024-08-12 18:16 UTC, Bitos88 commented on MovieFlick/StarsRateComponent.swift
> +
Eliminar todos los espacios que no sean necesarios. Como mucho un salto de linea entre cada elemento. Repasar todo el archivo

2024-08-13 07:09 UTC, franmu94 commented on MovieFlick/StarsRateComponent.swift
> +
Hecho

2024-08-14 07:15 UTC, Bitos88 approved these changes

2024-08-14 07:36 UTC, alexmaxu approved these changes

2024-08-16 08:26 UTC, merged