Added Swipe Card Component
watchorpass/MovieFlick pull request #8
Opened 2024-08-15 08:48 UTC by Bitos88

2024-08-15 09:09 UTC, alexmaxu approved these changes

2024-08-15 10:22 UTC, fran-6co requested changes
Awesome!
I checked the effects and the OK button image.
Take a look at my comments.

2024-08-15 10:22 UTC, fran-6co commented on MovieFlick/SwipeCardComponent.swift
> +            .swipeGestureModifier(offset: $offset, color: $color, buttonOpacity: $buttonOpacity)
que piensas si le añadimos un `.scaleEffect`?

propuesta:
`.scaleEffect(CGSize(width: 1-(abs(offset.width)/300), height: 1-(abs(offset.width)/300)))`

2024-08-15 10:22 UTC, fran-6co commented on MovieFlick/SwipeCardComponent.swift
> +                Image(systemName: "arrowshape.turn.up.right")
¿Cómo veis esta `Image(systemName: "checkmark")`?

2024-08-15 11:45 UTC, Bitos88 commented on MovieFlick/SwipeCardComponent.swift
> +                Image(systemName: "arrowshape.turn.up.right")
Si! lo que decidamos se pone, he puesto esa otra para que no fuera tan clásico. Pero ponemos la imagen que decidamos

2024-08-16 08:31 UTC, alexmaxu approved these changes

2024-08-16 08:31 UTC, fran-6co approved these changes

2024-08-16 08:31 UTC, merged